-- Fix Stable Masters per Axdrell https://github.com/dufernst/LegionCore-7.3.5/issues/73

UPDATE `creature_template` SET `gossip_menu_id` = 9821 WHERE `npcflag` = 4194433; 
UPDATE `creature_template` SET `AIName` = 'SmartAI' WHERE `npcflag` = 4194433 AND ScriptName = ''; 

-- entry 543 Nalesette Wildbringer // Patch 4.1.0 (2011-04-26): Fixed a bug where Nalesette would not function properly as a stable master.
DELETE FROM `creature_template` WHERE `entry`=543;
INSERT INTO `creature_template` (`entry`, `gossip_menu_id`, `minlevel`, `maxlevel`, `SandboxScalingID`, `ScaleLevelMin`, `ScaleLevelMax`, `ScaleLevelDelta`, `ScaleLevelDuration`, `exp`, `faction`, `npcflag`, `npcflag2`, `speed_walk`, `speed_run`, `speed_fly`, `scale`, `mindmg`, `maxdmg`, `dmgschool`, `attackpower`, `dmg_multiplier`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `unit_flags2`, `unit_flags3`, `dynamicflags`, `trainer_type`, `trainer_spell`, `trainer_class`, `trainer_race`, `minrangedmg`, `maxrangedmg`, `rangedattackpower`, `lootid`, `pickpocketloot`, `skinloot`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `spell1`, `spell2`, `spell3`, `spell4`, `spell5`, `spell6`, `spell7`, `spell8`, `PetSpellDataId`, `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `InhabitType`, `HoverHeight`, `Mana_mod_extra`, `Armor_mod`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ControllerID`, `WorldEffects`, `PassiveSpells`, `StateWorldEffectID`, `SpellStateVisualID`, `SpellStateAnimID`, `SpellStateAnimKitID`, `IgnoreLos`, `AffixState`, `MaxVisible`, `ScriptName`) VALUES 
(543, 9821, 40, 40, 28, 40, 60, 0, 0, 0, 80, 4194433, 0, 1, 1, 1.14286, 1, 106.4, 140.6, 0, 258, 1, 1500, 0, 1, 512, 2048, 0, 0, 3, 0, 0, 0, 74.1, 108.3, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'SmartAI', 0, 3, 1, 1, 1, 1, 0, 2, 0, '', '', 0, 0, 0, 0, 0, 0, 0, '');

DELETE FROM `gossip_menu_option` WHERE `MenuID` = 9821;
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) values('9821','0','5','I\'d like to stable my pet here.','14','4194304','0','0','0','0','0','0','','16131','0','0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) values('9821','1','1','I want to browse your goods.','3','128','0','0','0','0','0','0','','56613','0','0');
INSERT INTO `gossip_menu_option` (`MenuID`, `OptionIndex`, `OptionNPC`, `OptionText`, `OptionType`, `OptionNpcflag`, `OptionNpcflag2`, `ActionMenuID`, `ActionPoiID`, `BoxCoded`, `BoxMoney`, `BoxCurrency`, `BoxText`, `OptionBroadcastTextID`, `BoxBroadcastTextID`, `VerifiedBuild`) values('9821','2','0','I\'d like to heal and revive my battle pets.','1','1','0','0','0','0','1000','0','A small fee for supplies is required.','64115','66369','0');
